### ISSUE TITLE
Can you disable "Drag navigation bar to dismiss popup view"

### ISSUE THREAD

**Issue by barrettj** [kevin0571/STPopup#1]
Took a quick look and didn't see a way to disable the "Drag navigation bar to dismiss popup view" feature - is that something that I just overlooked or expected to be named differently?

**Comment by kevin0571** [comment]
No, currently STPopup does not have option to disable the "Drag to dismiss" feature. It does need a option for this. Will add it in next release.

**Comment by heyehao2008** [comment]
this popup just same as Uber App.  it's better if the mask backgroundView is blurring. awesome and beautiful！

**Comment by kevin0571** [comment]
@heyehao2008 right, will make the background view configurable.

**Comment by kevin0571** [comment]
@barrettj Added "draggable" property to STPopupNavigationBar. You could disable the "drag to dismiss" feature by setting:
```objc
self.popupController.navigationBar.draggable = NO;
```

**Comment by barrettj** [comment]
Works perfectly - thanks!
