### ISSUE TITLE
How to pass data to a popup?

### ISSUE THREAD

**Issue by Aleph72** [kevin0571/STPopup#113]
I haven't found any way to pass some data to the popup, is it even possible?
For example, I need to pass an array to the popup, so I can populate a tableView with data, then, upon selecting a row, some other data should be passed back to the view containing the popup.

**Comment by PrakashMaharjan** [comment]
Hi, @Aleph72 You can pass array as following:

For **eg**.
here **PopUpTableView** is the view to show in pop up.

**Obj C:**

PopUpTableView *popupTableVC = [[UIStoryboard storyboardWithName:@"Main" bundle:nil] instantiateViewControllerWithIdentifier:@"PopUpTableView"];
        **popupTableVC.toPassArray = arrayToPass;**
        
        STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:languageSelectionVC];

[popupController presentInViewController:self];

**Swift:**

let storyboard: UIStoryboard = UIStoryboard(name: "Main", bundle: nil)
let popupTableVC: PopUpTableView =  storyboard.instantiateViewController(withIdentifier: "PopUpTableView") as! PopUpTableView
popupTableVC.toPassArray = arrayToPass
let popup = STPopupController(rootViewController: popupTableVC)
popup.present(in: self, completion: nil)


Thanks

**Comment by Aleph72** [comment]
I have just figured it out myself. I haven't even tried it yet and I got your answer by mail.
Thank you very much.
