### ISSUE TITLE
UIScreen.main.bounds.size.width return 0 on rotation

### ISSUE THREAD

**Issue by SalvatoreAD** [kevin0571/STPopup#114]
i used "UIScreen.main.bounds.size.width" like this:
```
contentSizeInPopup = CGSize(width: UIScreen.main.bounds.width, height:UIScreen.main.bounds.height - 80)
        landscapeContentSizeInPopup = CGSize(width: UIScreen.main.bounds.height, height: UIScreen.main.bounds.width - 80)

```

but, if you rotate the screen, the library goes into error saying that both dimensions are 0

Can You help me?

**Comment by kevin0571** [comment]
@SalvatoreAD Could you paste the stack trace here?

**Comment by SalvatoreAD** [comment]
I solved using the native view controller. thanks anyway.
