### ISSUE TITLE
Add support for 3D Touch on iPhone 6S and 6S Plus

### ISSUE THREAD

**Issue by mad102190** [kevin0571/STPopup#12]
This seems like a perfect library for 3D Touch!

**Comment by talisk** [comment]
In my opinion, it's the best replacement scheme of 3D Touch in the other devices except for iPhone 6s and 6s Plus.

**Comment by kontextbewusst** [comment]
Would love to see this as well... I just tried to make it work without digging into the STPopup implementation, but no gold.

**Comment by kevin0571** [comment]
what about "peek" to show a blur preview of the popup, "pop" to show the final view?

**Comment by talisk** [comment]
The blur preview is unnecessary for the popup. Making the opening experience special on iPhone 6s and 6s Plus is a good idea.

**Comment by kevin0571** [comment]
Made http://github.com/kevin0571/STPopupPreview as an alternative for non 3D Touch devices.
