### ISSUE TITLE
Trying to use STPopup in app delegate

### ISSUE THREAD

**Issue by dflateau** [kevin0571/STPopup#126]
Apologies, I'm a little new at this...

I'm trying to use STPopup within the app delegate to popup a storyboard viewcontroller that has the contents of a push notification. So the presenting view controller will differ depending on where they are in the app. But I get the current view controller "theCurrentController" then I

`STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:newsPopupViewController];
[popupController presentInViewController:theCurrentController];`

where newsPopupViewController is a viewcontroller with the readme example of sizing (self.contentSizeInPopup = CGSizeMake(300, 400);
        self.landscapeContentSizeInPopup = CGSizeMake(400, 200);)

When I execute the [popupController presentInViewController:theCurrentController]; it halts in STPopupContoller.m at this line:

`NSAssert(!CGSizeEqualToSize(contentSize, CGSizeZero), @"contentSizeInPopup should not be size zero.");`

and tells me:
`MyApp[985:867847] [Snapshotting] Drawing a view (0x10800d5b0, UIView) that has not been rendered at least once requires afterScreenUpdates:YES.`
`MyApp[985:867847] *** Assertion failure in -[STPopupController contentSizeOfTopView], /Users/Davin/Documents/AM iOS app/AM-iosapp/Pods/STPopup/STPopup/STPopupController.m:578
`

I'm using the latest update. Trying to figure out where I'm going wrong, or what this error means in this sense - or if even this approach of using the "current view controller" will work. Thanks in advance.

**Comment by kevin0571** [comment]
Hi @dflateau, where did you set `contentSizeInPopup` of `newsPopupViewController`? Is it in the init function?

**Comment by dflateau** [comment]
I set it as in the readme example - in the init of the viewController I'm using for the popup (newsPopupViewController)

```
self.contentSizeInPopup = CGSizeMake(300, 400);
self.landscapeContentSizeInPopup = CGSizeMake(400, 200);
```

**Comment by kevin0571** [comment]
If the view controller is loaded from storyboard, you should either set the `contentSizeInPopup` in storyboard or in `awakeFromNib` method.
