### ISSUE TITLE
Any callback method when the popup is closed?

### ISSUE THREAD

**Issue by highviews** [kevin0571/STPopup#13]
I tried the following:
```
 [popupController presentInViewController:self completion:^{
    NSLog(@"Dismissed!");
}];
```

But this only works when the popup is finished appearing on the screen. I hope there must be some method somewhere but i just couldn't find it.

Please advice, thx!

**Comment by kevin0571** [comment]
@highviews if you manually dismiss the popupController, you can call: [self.popupController dismissWithCompletion:].
Or you should put your "dismiss callback" code in viewDidAppear of the viewController which is presenting the popupController. Hope this helps.
