### ISSUE TITLE
Is possible to change size of popupcontroller?

### ISSUE THREAD

**Issue by LorisOwna** [kevin0571/STPopup#14]
Is possible to change the size of the popup controller when is showed in the view?
I want to resize it when the keyboard is active.
I tried with this code
```
self.view.frame = CGRectMake(0, 0, self.view.bounds.width, 100)
```
but it doesn't work.

**Comment by kevin0571** [comment]
@LorisOwna currently it is not supported. I will add this feature in next release.

**Comment by AnthonyMDev** [comment]
+1 I would really like this feature

**Comment by kevin0571** [comment]
@AnthonyMDev Have you tried to set self.contentSizeInPopup? You can now set the contentSizeInPopup after the view controller is presented. The view size will be changed with animation.

**Comment by AnthonyMDev** [comment]
Awesome. I haven't tried that. I will do so! I appreciate it. Great library @kevin0571!
