### ISSUE TITLE
Crash when dismissing a modal QLPreviewController in iOS8 (ipad)

### ISSUE THREAD

**Issue by ijwelch** [kevin0571/STPopup#15]
Basically, present a QLPreviewController modally in iOS8 and crash when user dismisses it.

Traced to swizzle st_parentViewController.

I 'fixed' it by doing this in UIViewController+STPopup.m (but maybe there's a better way?):

- (UIViewController *)st_parentViewController
{
    @try {
        if (!self.popupController) {
            return [self st_parentViewController];
        }
    }
    @catch (NSException *exception) {

    }
    @finally {
        return [[self.popupController valueForKey:@"containerViewController"] parentViewController];
    }
}

That was a hard one to find:)

**Comment by kevin0571** [comment]
@ijwelch Actually, the swizzling of parentViewController is unnecessary, will delete it.
