### ISSUE TITLE
Unbalanced calls to begin/end appearance transitions....

### ISSUE THREAD

**Issue by ymantijunk** [kevin0571/STPopup#19]
We have an application which is using STPopup and we are facing an issue that "Unbalanced calls to begin/end appearance transitions" starts appearing if following code executed by popup launched using STPopup. The code is part of UIViewController which was launched by STPopup. It doesn't happen if the same code executed from normal VC (non-popup). Any idea?

-(void) sendSMS:(NSString *)phone message:(NSString *)message {
    
    MFMessageComposeViewController *controller = [[MFMessageComposeViewController alloc] init];
    
    if([MFMessageComposeViewController canSendText]) {
        
        controller.body = message;
        controller.recipients = [NSArray arrayWithObjects:phone, nil];
        
        controller.messageComposeDelegate = self;
        [self presentViewController:controller animated:YES completion:nil];
    } 
}

**Comment by ymantijunk** [comment]
We did more testing, even in your sample project and even X and drag to close stopped working after returning from the launched SMS window

**Comment by kevin0571** [comment]
@ymantijunk I tried present and dismiss MFMessageComposeViewController in my sample code, and then dismiss the STPopup, it works without issue. Can you paste the code of dismissing the MFMessageComposeViewController?

**Comment by Igor-Palaguta** [comment]
Have the same issue. Easy reproducible. Present to controller from popup controller modal view controller. Then make dismiss to presented controller. Swizzled st_dismissViewControllerAnimated instead of closing modal dismisses popup controller. And it leads to "Unbalanced calls to begin/end appearance"

**Comment by Igor-Palaguta** [comment]
Additional check self.presentedViewController fixes issue
```
- (void)st_dismissViewControllerAnimated:(BOOL)flag completion:(void (^)(void))completion
{
    if (!self.popupController || self.presentedViewController) {
        [self st_dismissViewControllerAnimated:flag completion:completion];
        return;
    }

    [self.popupController dismissWithCompletion:completion];
}
```
