### ISSUE TITLE
How use it for full screen presentation?

### ISSUE THREAD

**Issue by popei69** [kevin0571/STPopup#20]
Hi guys,

The main goal is to present my first viewController looking like a "classic" modal, and detail controllers pushed inside will be smaller.

I tried to set contentSizeInPopup with UIScreen bounds dimension and set transition with a full screen presentation, but it didn't work.

Is there anyway to do that in a proper way?

Thanks,
Ben

**Comment by kevin0571** [comment]
Hi, if you are going to present the view controller as a normal modal, just use "presentViewController" provided by UIViewController, instead of using STPopupController. contentSizeInPopup will only work if the view controller is pushed into a popup controller.

**Comment by popei69** [comment]
Hi kevin, thanks for your quick answer.
I already tried that, but as I said, I need details controllers with smaller sizes, and as I started with STPopupController, I can't really reimplement a use case only for make it full screen.
Best behaviour was to set contentSizeInPopup with maximum height minus navigationbar height.

**Comment by kevin0571** [comment]
@popei69 why do you need to reimplement it? you can make one view controller as both popup and normal view controller.

**Comment by popei69** [comment]
@kevin0571 I would like to optimise screen view depending of the device dimension (iphone4s vs iPad). On (really) small device, I will choose full screen, and not for bigger one. I wanted to keep same code as far as I can, but seems STPopup cannot "fake" a classic modal presentation in full screen. Thanks anyway.
