### ISSUE TITLE
Close popup when clicking outside of the controller

### ISSUE THREAD

**Issue by popei69** [kevin0571/STPopup#21]
Hi Kevin,

I would like to know if there is an easy way to make the popup close when clicking outside of the view.
I saw there is already something to drag the popup down that make it close, but nothing when clicking outside. I tried couple things but it didn't work well.  

Do you know if there is a way to do that? 

Thanks,
Ben

**Comment by kevin0571** [comment]
Hi @popei69 , you can get the background view of the popupController and add a gesture:
```objc
```

**Comment by popei69** [comment]
Hi @kevin0571 , thanks for your quick answer, it works like a charm ;)
