### ISSUE TITLE
How to handle keyboard for multiple text field in bottom sheet 

### ISSUE THREAD

**Issue by sumeet85** [kevin0571/STPopup#26]
I have used the multiple address text field on bottom sheet view controller 
When keyboard up it not able to touch and enter the value on it 
Please suggest me how to do that

**Comment by kevin0571** [comment]
@sumeet85 with "form sheet" style, I tested multiple text fields scenario, it works. and it should also work for "bottom sheet".
So when you are using only one text field, it works?

**Comment by sumeet85** [comment]
@kevin0571  Thanks for help
