### ISSUE TITLE
Tableview can't scroll down

### ISSUE THREAD

**Issue by barrettj** [kevin0571/STPopup#3]
I'm having an issue where if the view controller being displayed is a table view you're unable to scroll down.

I've made a rewritten "PopupViewController1" that you can drop into the sample to see what I mean.

https://gist.github.com/barrettj/fb7740136e2812c0bf46

**Comment by barrettj** [comment]
Strange - I just noticed that if you hit the next button and then go back you can scroll normally.

**Comment by barrettj** [comment]
Also I LOVE the popup - it works so much better than the (literally) half dozen others I've tried

**Comment by kevin0571** [comment]
@barrettj thank you!  
I think I know where the issue is, will fix it.  
As a temporary work around for you, I recommend you use UIViewController + UITableView instead of UITableViewController.

**Comment by barrettj** [comment]
It looks like scrolling is fixed, though now if you rotate the phone to landscape the view is the wrong size (the popup is the right size, but the table view goes to a strange small size)

**Comment by kevin0571** [comment]
@barrettj are you using UIViewController + UITableView now? If so, make sure you put your layout codes in viewDidLayoutSubviews instead of viewDidLoad, or using auto resizing/auto layout for the table view.

**Comment by barrettj** [comment]
I'm not as I don't have control over the view controller I'm displaying, it's from an external dependency.

**Comment by kevin0571** [comment]
@barrettj will try to fix this and release a new one.
