### ISSUE TITLE
Ton of Crashes

### ISSUE THREAD

**Issue by nikilster** [kevin0571/STPopup#33]
Hey!  We got like 120 crashes on this line:

UIResponder+STPopup.m line 35
-[UIResponder(STPopup) st_becomeFirstResponder]

Any ideas whats going on?  Thanks Kevin!

**Comment by kevin0571** [comment]
@nikilster Can you send out the detail stack trace? I used STPopup for two projects, never got a crash so far.

**Comment by nikilster** [comment]
Yup here are screenshots of our crash pages: 

bit.ly/stpopupstacktrace1
bit.ly/stpopupstacktrace2

Looks like the bug is only happening on iOS 8.

**Comment by kevin0571** [comment]
@nikilster can you check if there is any UITextField in your view controller defined as "assign"?

**Comment by kevin0571** [comment]
Will reopen if there is any further information.

**Comment by nikilster** [comment]
@kevin0571 there aren't any assign  UITextFields

**Comment by chika-kasymov** [comment]
I have same problems, for now uninstalled STPopUp

**Comment by kevin0571** [comment]
@chika-kasymov on iOS 8, if you subclass UITextField/UITextView and override "dealloc", the app will crash, it's a bug of UITextField/UITextView. Will it still crash even after you remove your subclass of UITextField?

**Comment by chika-kasymov** [comment]
@kevin0571 I use simple `UITextField`, but after debugging the reason of my crashes I think it's not your library. Sorry, for late response. To debug I removed `STPopUp` and `IQKeyboardManager` pods, but still have crashes.

**Comment by kevin0571** [comment]
@chika-kasymov thanks for the details. Let me know if there is anything related to STPopup. Will close this issue for now.

**Comment by kirti301290** [comment]
facing same issue there is lot of crashed
here is attched crash file
please help me 
[com.deepfood.tasktower_issue_crash_e6bd16a5aec94598997dd3b6919d6b22_DNE_0_v2.txt](https://github.com/kevin0571/STPopup/files/2984083/com.deepfood.tasktower_issue_crash_e6bd16a5aec94598997dd3b6919d6b22_DNE_0_v2.txt)
