### ISSUE TITLE
self.popupController is NULL after presenting MFMessageComposeViewController

### ISSUE THREAD

**Issue by nikilster** [kevin0571/STPopup#35]
We fire up a text message composer from clicking on one of the tableview cells.  After dismissing it with [self dismissViewControllerAnimated:completion:] the next time you click on one of the cells, self.popupController is NULL and we can no longer dismiss the controller with  [self.popupController dismiss].

**Comment by kevin0571** [comment]
@nikilster I tried to present a MFMessageComposeViewController in popup view controller, and dismiss it in delegate method:
```objc
- (void)messageComposeViewController:(MFMessageComposeViewController *)controller didFinishWithResult:(MessageComposeResult)result
{
        [controller dismissViewControllerAnimated:YES completion:nil];
}
```
Everything is fine and self.popupController is still there.
As you mentioned you called [self dismissViewControllerAnimated:completion:]  to dismiss the message compose view controller, is it a typo?

**Comment by nikilster** [comment]
Hmm so self is presenting the MFMessageComposeViewController so we're calling [self dismissViewControllerAnimated:completion:].

As far as I can tell thats correct?  What does calling dismiss on the controller variable do?

**Comment by kevin0571** [comment]
Nah, dismissViewControllerAnimated:completion: is used for dismiss view controller which is presented modally, according to Apple Doc:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/occ/instm/UIViewController/dismissViewControllerAnimated:completion:

**Comment by nikilster** [comment]
So the MFMessageComposeViewController is a modal controller and that's why we are dismissing it from self. The "Controller" variable is the MFComposer itself so I'm confused why we would call dismissViewController on that (like you said above - it's for dismissing modals that were presented by the caller).

**Comment by nikilster** [comment]
Hey Kevin - just wanted to make sure you saw this, thanks!

**Comment by kevin0571** [comment]
@nikilster as mentioned in Apple Doc about dismissViewControllerAnimated:completion: , if you call [self dismissViewController:completion] in this case, both popup controller and MFMessageComposeViewController will be dismissed. But this is not what you want right?
