### ISSUE TITLE
sometimes can not popUp when didSelectRow in a UITableView

### ISSUE THREAD

**Issue by beforeold** [kevin0571/STPopup#36]
you can reproduce this issue in your demo too.

**Comment by beforeold** [comment]
I'm afraid this issue appears when i popup a controller and dismiss it imedialtely. The 'didSelectRow' method did not respond at all until the popuped controller is dealloced. Looking forward to your reply. Thanks in advance.

**Comment by kevin0571** [comment]
@beforeold how do you dismiss the popup? Manually tap on the "X" button or call [self.popupController dismiss]?

**Comment by beforeold** [comment]
well, in fact, I can not neither scroll my tableView during a short time about 1or2 second after the popuped controller dismissed.

**Comment by kevin0571** [comment]
Take a look at this issue #9 , should be the same?

**Comment by beforeold** [comment]
Yeah, exactly.
