### ISSUE TITLE
failed to run the example

### ISSUE THREAD

**Issue by qiulang** [kevin0571/STPopup#38]
I just can't make example run even I have added STPopup.framework to example project, I still hit the error "dyld: Library not loaded: @rpath/STPopup.framework/STPopup
  Referenced from: /var/mobile/Containers/Bundle/Application/AB81B362-72D7-4305-8F42-C1AEEE1C0F49/STPopup.app/STPopup
  Reason: image not found"

Why is that ?

**Comment by kevin0571** [comment]
@qiulang try to clone the latest commit, should be bundle identifier issue and I think it's fixed.

**Comment by benaneesh** [comment]
This still happening with the latest clone. Works in the simulator though.
