### ISSUE TITLE
Swift version please! Thanks!

### ISSUE THREAD

**Issue by haducloc** [kevin0571/STPopup#4]

**Comment by kevin0571** [comment]
@haducloc Alright. But have you tried bridge the STPopup.h into your swift project?

**Comment by chenzeyu** [comment]
@haducloc if you are using Cocoapods to manage your dependencies, it is very easy to integrate an obj-c project to your swift project.

**Comment by barrettj** [comment]
I'm using this via cocoapods in my swift project and it works great

**Comment by m-t-space** [comment]
I would love an example using swift. My Obj-C is sub par...
