### ISSUE TITLE
HideNavigation Bar

### ISSUE THREAD

**Issue by girubhai** [kevin0571/STPopup#5]
How can i Hide the Navigation Bar?
I did 
[STPopupNavigationBar appearance].hidden = YES;

with no success.Plz help.

**Comment by kevin0571** [comment]
@girubhai navigation bar hidden will be supported in next release.
and I think it would be something like self.popupController.navigationBar.hidden = YES, so it's not going to be configured by appearance as it should not be part of it.

**Comment by girubhai** [comment]
@kevin0571 
self.popupController.navigationBar.hidden = YES
also not working,Anyway when will be next release?

**Comment by kevin0571** [comment]
@girubhai as this is an open source project, i can't promise the release date, maybe this weekend. if that is urgent for you, i recommend you fork the repo and try to resolve the issue.
