### ISSUE TITLE
Dismiss animation use spring is not good way

### ISSUE THREAD

**Issue by bawn** [kevin0571/STPopup#51]
I found the spring animation although it seems has been complete but did not actually complete

detail see gif

spring animation

![2016-03-03 16_32_41](https://cloud.githubusercontent.com/assets/7238866/13488769/376896de-e15e-11e5-90fb-0627b40869d7.gif)

normal animation

```
[UIView animateWithDuration:[self transitionDuration:transitionContext] - 0.3 delay:0 options:UIViewAnimationOptionCurveEaseOut
```

![2016-03-03 16_36_35](https://cloud.githubusercontent.com/assets/7238866/13488785/4c2689dc-e15e-11e5-85a6-244f4b0e5d79.gif)

**Comment by mixdesign** [comment]
I have the same issue. 
I think there shouldn't be blocking while spring related actions working under the hood.

**Comment by kevin0571** [comment]
Alright, I'm going to remove "spring" in dismissing animation.

**Comment by kevin0571** [comment]
Same as #9 #36
