### ISSUE TITLE
Help : Present Multiple STPopup at sametime

### ISSUE THREAD

**Issue by hardikamal** [kevin0571/STPopup#52]
I am using UILocalnotification...on receiving the notification i open STPopup when the app is in active mode...but if multiple notifications are received at same time...how do i open the multiple popup...above each other and dismiss them sequentially....I tried opening viewcontroller but receiving this error `Warning: Attempt to present <NotificationViewController: 0x7fc033b43900> on <UINavigationController: 0x7fc031859600> whose view is not in the window hierarchy!`

Thanks

**Comment by kevin0571** [comment]
@hardikamal I think you should present the popup on the top view controller, which means if you have already presented a popup on NotificationViewController, you will need to present the next popup on NotificationViewController.presentedViewController.
But I don't think presenting multiple popups is a good idea. Instead, you can keep a shared instance of STPopupController, and when you are going to present the second popup, you can push it to the existing STPopupController.
```objc
[_sharedPopupController pushViewController:viewController animated:YES];
```

**Comment by hardikamal** [comment]
@kevin0571 Thanks solved
