### ISSUE TITLE
Enable to hide navigation bar

### ISSUE THREAD

**Issue by Sukhrob** [kevin0571/STPopup#53]
I saw the issue https://github.com/kevin0571/STPopup/issues/5 where it says the support to hide a navigation bar is added. But, when I try to hide it using the code below, it crashes.

    CustomViewController *viewController = [[CustomViewController alloc] init];
    STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:viewController];
    popupController.navigationBarHidden = YES; // Crashes

    *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'contentSizeInPopup should not be size zero.'

I set both "contentSizeInPopup" and "landscapeContentSizeInPopup" properly. Because, when I remove the line where there is a code to hide a navigation bar, it works.

**Comment by kevin0571** [comment]
@Sukhrob HI, where do you set the contentSizeInPopup? Is it in "init" method?

**Comment by Sukhrob** [comment]
@kevin0571 Thanks for your quick reply. I am setting it in viewDidLoad. Now, I tried in init and it worked. Thanks for such an awesome library :+1:

**Comment by SalvatoreAD** [comment]
I have this problem in swift
