### ISSUE TITLE
Adjust top position

### ISSUE THREAD

**Issue by vietnguyen09** [kevin0571/STPopup#56]
Hi there,

I would like to Adjust top margin because I have ADS banner at bottom, so if I adjust height to see ads then my popup view is too low.

I've been trying to add CGrectMake but doesn't work.

Secondly, I want to make close button position `X` to right instead of left.

Thanks

**Comment by kevin0571** [comment]
@vietnguyen09 One workaround here, set popupController.containerView.transform with translation to adjust the Y position, but may have some unexpected behaviors.
If you want to move "X" button to the right, you may need to set the leftBarButtonItem to an empty bar button item and create your own rightBarButtonItem. But this is not recommended because "Cancel"/"Close" action should be on left side.

**Comment by vietnguyen09** [comment]
For anyone who have similar question.

this code for hide leftBarButtonItem and show rightBarButtonItem and close selector.

> 
        UIButton* rightButton = [UIButton buttonWithType:UIButtonTypeCustom];
        [rightButton setImage:[UIImage imageNamed:@"popup-close"] forState:UIControlStateNormal];
        [rightButton setTintColor:[UIColor whiteColor]];
        [rightButton addTarget:self action:@selector(rightBarButtonItemAction:) forControlEvents:UIControlEventTouchUpInside];
        [rightButton sizeToFit];
        rightButton.titleEdgeInsets = UIEdgeInsetsMake(0, -50, rightButton.titleLabel.frame.size.width, rightButton.titleLabel.frame.size.height);
        UIBarButtonItem* rightBarButtonItem = [[UIBarButtonItem alloc] initWithCustomView:rightButton];
        self.navigationItem.rightBarButtonItem = rightBarButtonItem;
        self.navigationItem.hidesBackButton = YES;
	- (IBAction)rightBarButtonItemAction:(id)sender
	{
		[self.popupController dismiss];
	}

After a while thinking about adjust top position, I've just realized that, this is not necessary like **kevin0571** said `may have some unexpected behaviors` but anyway, I've figure out the way to do that for anyone need.

In file STPopupController.m find this code

> CGFloat containerViewY = (_containerViewController.view.bounds.size.height - containerViewHeight) / 2;

And just edit `/ 2` to any number you want, it's will change the margin top of the popup view.

@kevin0571 I agree with you about change top position but I don't know why you said cancel/close should be on left side? is it the Europeans and the Americas are lefthanded is the reason I guess?

**Comment by kevin0571** [comment]
@vietnguyen09 I think right bar button is supposed to be action like "send", "compose", same rule as a full screen modal view. But if you don't have right bar button on your popup, I think it's ok to put close button on right, I did see some apps do this. Just that personally I prefer to keep them consistent.

**Comment by saintjab** [comment]
Nice catch, I was looking for such implementation. Thanks @kevin0571 and @vietnguyen09
