### ISSUE TITLE
UINavigationBar items not appearing 

### ISSUE THREAD

**Issue by daisyramos317** [kevin0571/STPopup#59]
![enablepush](https://cloud.githubusercontent.com/assets/6922240/14324920/f1f298e6-fbf4-11e5-87d5-ac2ebfc9c114.PNG)

I am loading the view controller from a storyboard and STPopup Controller is instantiated here
` let storyboardID = UIStoryboard(name: "Push", bundle: nil)
            let popupController: STPopupController = STPopupController(rootViewController: storyboardID.instantiateViewControllerWithIdentifier("enablePush"))
            popupController.containerView.layer.cornerRadius = 4
            popupController.presentInViewController(self)`

In viewDidLoad() of this view controller I have:

` self.contentSizeInPopup = CGSizeMake(300, 200)
        self.landscapeContentSizeInPopup = CGSizeMake(400, 200)
        self.navigationItem.rightBarButtonItem?.image = UIImage(named: "dismissPushIcon")
        self.navigationItem.title = "Enable Push"`

However the navigation bar remains empty as in the picture above.

**Comment by kevin0571** [comment]
@daisyramos317 the code you posted should work. But can you try adding navigation items in storyboard instead?

**Comment by daisyramos317** [comment]
I did try adding navigation items in Storyboard as well it still doesn't appear.
