### ISSUE TITLE
Call notification after dismiss

### ISSUE THREAD

**Issue by vietnguyen09** [kevin0571/STPopup#61]
Hi there,

I want to make a `NSNotificationCenter` when popup is dismiss but it isn't work.

First I using `NSNotificationCenter ` to register `login_success` event.

> [[NSNotificationCenter defaultCenter] postNotificationName:@"login_success" object:nil];
> [self.popupController dismiss];

And then I call it in parent view.

> - (void)viewDidAppear:(BOOL)animated
> {
>     [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(chot_so_login_success) name:@"chot_so_login_success" object:nil];
> }
> 

But nothing happen, how can I handler event after popup closed?

Thanks for help

**Comment by khunshan** [comment]
is it resolved?
