### ISSUE TITLE
Dismiss by background tap is not working

### ISSUE THREAD

**Issue by vietnguyen09** [kevin0571/STPopup#64]
I've done like readme but it's not working, it's a bug?
NSlog trigger show fine but popup never close.

	- (void)showPopupDaudit{
		STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:[POPViewController new]];
		[STPopupNavigationBar appearance].tintColor = MP_HEX_RGB(MAINCOLOR);
		popupController.containerView.layer.cornerRadius = 4;
		if (NSClassFromString(@"UIBlurEffect")) {
			UIBlurEffect *blurEffect = [UIBlurEffect effectWithStyle:UIBlurEffectStyleDark];
			popupController.backgroundView = [[UIVisualEffectView alloc] initWithEffect:blurEffect];
		}
		[popupController.backgroundView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(backgroundViewDidTap:)]];
		[popupController presentInViewController:self];
	}
	- (IBAction)backgroundViewDidTap:(id)sender
	{
		[self.popupController dismiss];
		NSLog(@"Tapping in background.");
	}

**Comment by kevin0571** [comment]
@vietnguyen09 think you are referring self.popupController in a wrong view controller. backgroundViewDidTap should be called in your POPViewController.

**Comment by vietnguyen09** [comment]
It's error 
`backgroundViewDidTap]: unrecognized selector sent to instance 0x15780b7b0`

Main.m

	[popupController.backgroundView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:self action:@selector(backgroundViewDidTap)]];

Pop.h
`- (IBAction)backgroundViewDidTap;`

Pop.m

	- (IBAction)backgroundViewDidTap
	{
	//    [self.popupController dismiss];
		NSLog(@"Tapping in background2.");
	}

**Comment by kevin0571** [comment]
The target is not "self" in this case. Please read more about how to use gesture recognizer.

**Comment by vietnguyen09** [comment]
I've just copied your example in readme, I've searched in your example but its not contains any example about dismiss popup by tapping background.

**Comment by vietnguyen09** [comment]
Please help

**Comment by MartienB** [comment]
@vietnguyen09 You should set the <code>POPViewController</code> as target, not the <code>STPopupController</code>.

Main.m:
```
    POPViewController *vc = [[POPViewController alloc] init];
    STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:vc];
    [popupController.backgroundView addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:vc action:@selector(backgroundViewDidTap)]];
```

POPViewController.h:
```
-(void)backgroundViewDidTap;
````

POPViewController.m:
```
- (void)backgroundViewDidTap
{
    [self.popupController dismiss];
}
```

**Comment by StasMalinovsky** [comment]
In iOS 11 this solution will not work. Here is the suggestion:
`[[(UIVisualEffectView *)popupController.backgroundView contentView] addGestureRecognizer:[[UITapGestureRecognizer alloc] initWithTarget:vc action:@selector(backgroundViewDidTap)]];`
