### ISSUE TITLE
Notification or completion method when popup is closed or dismissed?

### ISSUE THREAD

**Issue by khunshan** [kevin0571/STPopup#65]
I want to add a custom method when a popup is closed by pressing the left bar button or by swiping the navigation bar downwards.

The problem is I am showing a pop up in which I have to keep a check that if the user closed or swiped it then the parent view controller must know that it is closed.

Overriding  

>     override func dismissViewControllerAnimated(flag: Bool, completion: (() -> Void)?) {}

did not solve the issue.

**Comment by kevin0571** [comment]
Not going to have a enhancement for this specific case. But think it could be done by observing popupController's presented attribute.
