### ISSUE TITLE
Animation problem on Tabbar

### ISSUE THREAD

**Issue by nottix** [kevin0571/STPopup#66]
Hi,

we're using latest version on STPopup in our app. 
There is a problem when we present the STPopup from a ViewController contained into Tabbar.

These are the steps:
1. Present STPopup
2. STPopup appears for about 500ms without animation
3. STPopup disappears
4. STPopup appears with animation

Thank you

**Comment by kevin0571** [comment]
@nottix Hi, I did exactly the same in my own app(present a popup from view controller containered into tab bar), everything works fine. Can you show me some demo code?

**Comment by CeccoCQ** [comment]
Hi @kevin0571 ,
I've the same problem. The popup appears two times, the first without animation and the second about 300ms later.

In my specific case, I've a Tabbar and a FirstViewController where I set a TableViewCell with a callback:

```
AlertNotificationListTableViewCell *cell = [tableView dequeueReusableCellWithIdentifier:@"AlertNotificationCell" forIndexPath:indexPath];
        cell.selectionStyle = UITableViewCellSelectionStyleNone;
        [cell setupWithAlertNotifications:_alertNotifications homeNotificationCallback:^(AlertNotification *alertNotification, int index) {
            [AlertNotificationController handleAlertNotification:alertNotification fromViewController:self];
        } closeCallback:^(FsHomeNotification *homeNotification, int index) {
           ....
        }];
        return cell;

```

When user clicks on cell, I invoke handleAlertNotification:
```
UIStoryboard *storyboard = [UIStoryboard storyboardWithName:@"Notification" bundle:nil];
        NotificationAlertTableViewController *notificationAlertTableViewController = [storyboard instantiateViewControllerWithIdentifier:@"NotificationAlertView"];
        [notificationAlertTableViewController setTitle:@"INFO"];
        notificationAlertTableViewController.homeNotification = homeNotification;
        
        STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:notificationAlertTableViewController];
        [popupController presentInViewController:viewController];
```

**Comment by kevin0571** [comment]
@CeccoCQ in your case, can you put a breakpoint in "handleAlertNotification" or NSLog something in "handleAlertNotification"? Want to check if you accidentally call "handleAlertNotification" twice.

**Comment by CeccoCQ** [comment]
Hi @kevin0571,
In this code already there is a NSLog, and I can confirm that this method is invoked only one time.

**Comment by kevin0571** [comment]
Is "handleAlertNotification" executed in main thread?

**Comment by CeccoCQ** [comment]
Yes, I've also surrounded the method with:
```
[[NSOperationQueue mainQueue] addOperationWithBlock:^ {
                
                //Your code goes in here
            [FsNotificationController handleHomeNotification:homeNotification fromViewController:self];
                
            }];
```

but same problem.

**Comment by CeccoCQ** [comment]
@kevin0571 Is there a way to disable animations?

**Comment by kevin0571** [comment]
@CeccoCQ there is no way to disable animations with STPopupController for now. but you can try [UIView setAnimationsEnabled:NO] and re-enable animation after popup is presented.
is the issue above resolved? I still can not replicate it.

**Comment by CeccoCQ** [comment]
@kevin0571 with [UIView setAnimationsEnabled:NO] all works, thanks.
