### ISSUE TITLE
Rounded corners on popup controller

### ISSUE THREAD

**Issue by AnthonyMDev** [kevin0571/STPopup#67]
My popup controller has sharp corners, while the example images in the README show the popup with rounded corners. How did you achieve this effect?

**Comment by kevin0571** [comment]
@AnthonyMDev as shown in example project, you can use popupController.containerView.layer.cornerRadius to set rounded corners.

**Comment by tylerjames** [comment]
For anyone that lands on this same issue: there is no longer an exposed `containerView` property.

You can set the corner radius of the popup like this now:
`popupController.cornerRadius = 3.0f`

**Comment by kevin0571** [comment]
@tylerjames containerView was exposed since v1.6.0, not sure which version you are using.
