### ISSUE TITLE
Adjust contentSizeInPopup after keyboard is shown

### ISSUE THREAD

**Issue by tylerjames** [kevin0571/STPopup#70]
Hi,

I'd like to have a bottom sheet popup that contains a textfield near the bottom. The main content of the popup is a chat window so I'd like it to have a pretty decent height when the keyboard is down, and then adjust to be a bit smaller when the the keyboard is shown so that the top of the popup does not go higher than the top of the screen.

I've tried adjusting the contentSizeInPopup after the keyboard is showing but for some reason this causes the sheet to move down behind the keyboard, almost as if the offsetY transform as been reset. 

Is there any way to adjust the size when the keyboard is up so that the top of the "bottom sheet" does not go above the top of the screen?

**Comment by kevin0571** [comment]
@tylerjames did you try to adjust the contentSizeInPopup in "textFieldDidBeginEditing" delegate method instead of keyboard observer? I tried in "textFieldDidBeginEditing", the popup won't be covered by keyboard.

**Comment by tylerjames** [comment]
Thanks, that seems to work.

**Comment by tylerjames** [comment]
The only slight issue with this is that `textFieldDidBeginEditing` is fired before `keyboardWillShow` which makes it hard to know how big the keyboard is going to be. Kind of a pain, especially now that we have 3rd party keyboards.
