### ISSUE TITLE
STPopup.framework Use of

### ISSUE THREAD

**Issue by AlanZhaos** [kevin0571/STPopup#72]
Need adapter IOS7,Cannot use ‘Carthage’，Can send me a alone ‘STPopup.framework’, My mailbox is 905223320@qq.com

**Comment by kevin0571** [comment]
@AlanZhaos If you want to use framework with iOS 7, you need to clone the project and do it yourself. Can refer to https://www.raywenderlich.com/65964/create-a-framework-for-ios
