### ISSUE TITLE
Incorrect popup movement if keyboard triggered in WKWebview

### ISSUE THREAD

**Issue by HarukaMa** [kevin0571/STPopup#74]
If the keyboard is triggered by text input in a webpage contained in `WKWebView`, `getCurrentTextInputInView` will return `WKContentView` as `currentTextInput`. It will then incorrectly calculate the distance needs to be moved of the popup view. Usually it will make the popup move outside the screen.

Didn't test with `UIWebView`.

**Comment by kevin0571** [comment]
@HarukaMa this is tricky, think the adjustment of popup position should be disabled in this case, let the web view handle the content offset adjustment.

**Comment by HarukaMa** [comment]
yep, I'm doing this right now.

```objc
if ([NSStringFromClass([currentTextInput class]) isEqualToString:@"WKContentView"]) {
        return;
}
```
