### ISSUE TITLE
Expose spacing property for adjustContainerViewOrigin

### ISSUE THREAD

**Issue by jedmund** [kevin0571/STPopup#76]
It would be really nice if the `spacing` property used in `adjustContainerViewOrigin` were exposed as something users could set. 

Right now, its hard-coded to 5pt, but that doesn't really mesh well with our design, where the default spacing unit is 8pt (or where we'd be using it, 16pt).

I can make a PR for this if it would help.

**Comment by jedmund** [comment]
I made a PR for this. Its #77. Would be nice to get it merged!

**Comment by kevin0571** [comment]
@jedmund Sorry for late reply. The behavior of adjustContainerViewOrigin will be slightly different in the upcoming version(containerView will be vertically centered if there is enough space). So will not merge it for now.

**Comment by kevin0571** [comment]
1.8.2: Popup view will be vertical-centered if there is enough space when keyboard shows up.
