### ISSUE TITLE
Tap Background To Dismiss

### ISSUE THREAD

**Issue by nikilster** [kevin0571/STPopup#8]
Hey!  Awesome library! Thanks for making it!!!

Two quick questions:

1. How did you get the rounded corners in the demo page?
2. Can you tap on the background to dismiss the modal?

Thanks again!

**Comment by nikilster** [comment]
Okay figured out #1 by looking at the example project - would be awesome to add that to the tutorial!

**Comment by kevin0571** [comment]
Latest release exposes "backgroundView" of STPopupController.
You can addGesture to "popupController.backgroundView" to achieve what you want.
