### ISSUE TITLE
UIVisualEffectView 0x149a68280> is being asked to animate its opacity.

### ISSUE THREAD

**Issue by multinerd** [kevin0571/STPopup#81]
everywhere i use this framework in my code, i get the debugger message `<UIVisualEffectView 0x149a68280> is being asked to animate its opacity. This will cause the effect to appear broken until opacity returns to 1.`

code used
--

    RTGDatesTVC *cal = [[UIStoryboard storyboardWithName:@"RTGSales"
                                                  bundle:nil] instantiateViewControllerWithIdentifier:@"RTGDatesTVC"];
    cal.dateDelegate = self;
    cal.contentSizeInPopup = CGSizeMake((MNScreen_Size).width, 400);
    cal.landscapeContentSizeInPopup = CGSizeMake((MNScreen_Size).width, 200);
    cal.title = @"Pick a date";
    cal.listOfDates = listOfDateRanges;
    
    STPopupController *popupController = [[STPopupController alloc] initWithRootViewController:cal];
    if (NSClassFromString(@"UIBlurEffect")) {
        popupController.backgroundView = [[UIVisualEffectView alloc] initWithEffect:[UIBlurEffect effectWithStyle:UIBlurEffectStyleDark]];
    }
    popupController.style = STPopupStyleBottomSheet;
    [popupController presentInViewController:self];

**Comment by kevin0571** [comment]
@multinerd it's because UIVisualEffectView is used as the background view. The visual effect will be sort of not working when STPopup is animating the background view, but everything will be fine after the animation is finished. It won't actually affect the UI though.

**Comment by multinerd** [comment]
ok, thanks for clarifying
