### ISSUE TITLE
STPOPUP SEMANTIC ISSUE

### ISSUE THREAD

**Issue by yogesh2209** [kevin0571/STPopup#82]
It was working fine initially.
But, when I copied my project and tried running it after pasting it in a different folder.
I got this error. Please help. URGENT

PLEASE !!

![screen shot 2016-12-02 at 2 26 11 pm](https://cloud.githubusercontent.com/assets/8548476/20828059/a66972b4-b89b-11e6-9c2e-0c9c57fe0ebd.png)
![screen shot 2016-12-02 at 2 26 19 pm](https://cloud.githubusercontent.com/assets/8548476/20828060/a66c4e94-b89b-11e6-8a57-b3ecc5f45257.png)

**Comment by kevin0571** [comment]
@yogesh2209 there is no delegate in STPopupController since the first version. I guess you were using a forked version of STPopup that provides delegate?
