### ISSUE TITLE
Unable to read the license file

### ISSUE THREAD

**Issue by Zingoer** [kevin0571/STPopup#85]
I got this error when I try to update the STPopup through CocoaPod
> [!] Unable to read the license file `/Users/Zingoer/Developer/Projects/milieu_ios_milieucities/Milieu/Pods/STPopup/LICENSE` for the spec `STPopup (1.8.1)`

**Comment by kevin0571** [comment]
@Zingoer Unable to reproduce issue and LICENSE file is actually there with 1.8.1. You could safely ignore this warning.
