### ISSUE TITLE
Recognizing tap right after dismiss

### ISSUE THREAD

**Issue by nikilster** [kevin0571/STPopup#9]
Another question - after I dismiss the modal, the next tap (if I tap quickly) isn't registered by the main view controller.  Any thoughts on how to fix this?  Thanks!

**Comment by nikilster** [comment]
Did some debugging - I think this is because the view controller is being dismissed with animation - the animation visually finishes before the modal page is removed from the UI View hierarchy / stack.  It seems to work if we do 

    [_containerViewController dismissViewControllerAnimated:NO completion:^{

and dismiss with the viewcontrolleranimated property = NO

**Comment by kevin0571** [comment]
@nikilster that is because the transition has "easeOut" curve, so the animation is not finished even though it looks like finished. You could try to disable the animation curve option.
