### ISSUE TITLE
Warning: Attempt to present <STPopupContainerViewController: 0x7fe9caeabbf0> on <HomeViewController: 0x7fe9cb04f200> whose view is not in the window hierarchy!

### ISSUE THREAD

**Issue by GitCod-Man** [kevin0571/STPopup#91]
Warning: Attempt to present <STPopupContainerViewController: 0x7fe9caeabbf0> on <HomeViewController: 0x7fe9cb04f200> whose view is not in the window hierarchy!

**Comment by kevin0571** [comment]
Closing this for now since I can't reproduce the issue.
