### ISSUE TITLE
Present popup on Presentted View Controller 

### ISSUE THREAD

**Issue by kmuddapu** [kevin0571/STPopup#94]
How to present popup on Presentedviewcontroller?

**Comment by rjpalermo1** [comment]
[self.popupController pushViewController:[[UIStoryboard storyboardWithName:@"yourVC" bundle:nil] instantiateViewControllerWithIdentifier:@"yourVC"] animated:YES];

**Comment by kevin0571** [comment]
```
[popupController presentInViewController:self.presentedViewController];
```
